
SELECT * FROM LAYOFFS;

-- REMOVE DUPLICATES.

CREATE TABLE LAYOFFS_STAGE2
LIKE LAYOFFS;

SELECT* FROM LAYOFFS_STAGE2;


INSERT LAYOFFS_STAGE2
SELECT* FROM LAYOFFS;

SELECT* FROM LAYOFFS_STAGE2;


-- STEP 1(REMOVING DUPLICATES)- IDENTIFYING DUPLICATES

SELECT*,
ROW_NUMBER() OVER (
PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGE2;

WITH DUPLICATE_CTE AS
(
SELECT*,
ROW_NUMBER() OVER (
PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGE2
)
SELECT* FROM DUPLICATE_CTE
WHERE ROW_NUM >1; 

CREATE TABLE `layoffs_stage3` (
  `company` text,
  `location` text,
  `industry` text,
  `total_laid_off` int DEFAULT NULL,
  `percentage_laid_off` text,
  `date` text,
  `stage` text,
  `country` text,
  `funds_raised_millions` int DEFAULT NULL,
  `ROW_NUM` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT* FROM LAYOFFS_STAGE3;

INSERT  INTO LAYOFFS_STAGE3
SELECT*,
ROW_NUMBER() OVER(
PARTITION BY COMPANY,LOCATION,INDUSTRY,TOTAL_LAID_OFF,PERCENTAGE_LAID_OFF,`DATE`,STAGE,COUNTRY,FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFFS_STAGE2;

DELETE
FROM LAYOFFS_STAGE3
WHERE ROW_NUM > 1;

SELECT* FROM LAYOFFS_STAGE3;


-- STANDARDIZING DATA

SELECT DISTINCT(COMPANY)
FROM LAYOFFS_STAGE3;

SELECT COMPANY,TRIM(COMPANY)
FROM LAYOFFS_STAGE3;

UPDATE LAYOFFS_STAGE3
SET COMPANY = TRIM(COMPANY);

SELECT DISTINCT COUNTRY,TRIM(TRAILING '.' FROM COUNTRY)
FROM LAYOFFS_STAGE3
ORDER BY 1;

UPDATE LAYOFFS_STAGE3
SET COUNTRY = TRIM(TRAILING '.' FROM COUNTRY)
WHERE COUNTRY LIKE 'UNITED STATES%';

SELECT DISTINCT COUNTRY
FROM LAYOFFS_STAGE3;


SELECT* 
FROM LAYOFFS_STAGE3
WHERE INDUSTRY LIKE 'CRYPTO%';

UPDATE LAYOFFS_STAGE3
SET INDUSTRY = 'CRYPTO'
WHERE INDUSTRY LIKE 'CRYPTO%';

SELECT `DATE`
FROM LAYOFFS_STAGE3;


UPDATE layoffs_stage3
SET `date` = 
    CASE
        WHEN `date` IS NOT NULL AND `date` != 'NULL' THEN STR_TO_DATE(`date`, '%m/%d/%Y')
        ELSE NULL  
    END;
    
    ALTER TABLE LAYOFFS_STAGE3
    MODIFY COLUMN `DATE` DATE;
    
    

-- Null and blank values
select* FROM LAYOFFS_STAGE3
WHERE TOTAL_LAID_OFF  IS NULL
AND PERCENTAGE_LAID_OFF IS NULL;
 
 
 UPDATE LAYOFFS_STAGE3
 SET INDUSTRY= null
 WHERE INDUSTRY = '';
   
 SELECT * FROM LAYOFFS_STAGE3
 WHERE INDUSTRY IS NULL
 OR INDUSTRY= '';
 

 SELECT*
 FROM LAYOFFS_STAGE3 T1
 JOIN LAYOFFS_STAGE3 T2
    ON T1.COMPANY=T2.COMPANY
WHERE (T1.INDUSTRY IS NULL IS NULL OR T1.INDUSTRY='')
AND T2.INDUSTRY IS NOT NULL;    

UPDATE LAYOFFS_STAGE3 T1
JOIN LAYOFFS_STAGE3 T2
   ON T1.COMPANY=T2.COMPANY
SET T1.INDUSTRY = T2.INDUSTRY
WHERE (T1.INDUSTRY IS NULL OR T1.INDUSTRY ='')
AND T2.INDUSTRY IS NOT NULL;

SELECT* 
FROM layoffs_stage3
 WHERE COMPANY = 'AIRBNB';
 
 SELECT *
 FROM LAYOFFS_STAGE3
 WHERE TOTAL_LAID_OFF IS NULL
 AND PERCENTAGE_LAID_OFF IS NULL;


DELETE
 FROM LAYOFFS_STAGE3
 WHERE TOTAL_LAID_OFF IS NULL
 AND PERCENTAGE_LAID_OFF IS NULL;
 
 SELECT*
 FROM  LAYOFFS_STAGE3;
 
 ALTER TABLE LAYOFF_STAGE3
 DROP COLUMN ROW_NUM;
 
 
 -- Exploratory Data Analysis
 
 SELECT * 
 FROM LAYOFFS_STAGE3;
 
 SELECT MAX(TOTAL_LAID_OFF),MAX(PERCENTAGE_LAID_OFF)
 FROM LAYOFFS_STAGE3;
 
 SELECT*
 FROM LAYOFFS_STAGE3
 WHERE PERCENTAGE_LAID_OFF=1
 ORDER BY funds_raised_millions DESC;
 
 SELECT COMPANY,SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COMPANY
 ORDER BY 2 DESC;
 
 SELECT MIN(`DATE`),MAX(`DATE`)
 FROM LAYOFFS_STAGE3;
 
 SELECT INDUSTRY,SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY INDUSTRY
 ORDER BY 2 DESC;
 
 
SELECT COUNTRY,SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COUNTRY
 ORDER BY 2 DESC;
 
 SELECT YEAR(`DATE`),SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY YEAR(`DATE`)
 ORDER BY 1 DESC;

SELECT STAGE,SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY STAGE
 ORDER BY 2 DESC;
 
 SELECT COMPANY,AVG(PERCENTAGE_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COMPANY
 ORDER BY 2 DESC;

SELECT SUBSTRING(`DATE`,1,7) AS `MONTH`,SUM(TOTAL_LAID_OFF)
FROM LAYOFFS_STAGE3
WHERE SUBSTRING(`DATE`,1,7) IS NOT NULL
GROUP BY `MONTH`
ORDER BY 1 ASC; 

 SELECT COMPANY,SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COMPANY
 ORDER BY 2 DESC;

WITH ROLLING_TOTAL AS
(
SELECT SUBSTRING(`DATE`,1,7) AS `MONTH`,SUM(TOTAL_LAID_OFF) AS TOTAL_OFF
FROM LAYOFFS_STAGE3
WHERE SUBSTRING(`DATE`,1,7) IS NOT NULL
GROUP BY `MONTH`
ORDER BY 1 ASC
)
SELECT `MONTH`, TOTAL_OFF,
SUM(TOTAL_OFF)OVER(ORDER BY`MONTH`) AS ROLLING_TOTAL
FROM ROLLING_TOTAL;

SELECT COMPANY,SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COMPANY
 ORDER BY 2 DESC;

SELECT COMPANY,YEAR(`DATE`),SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COMPANY,YEAR(`DATE`)
 ORDER BY 3 DESC;
 
 WITH COMPANY_YEAR (COMPANY,YEARS,TOTAL_LAID_OFF) AS
 (
 SELECT COMPANY,YEAR(`DATE`),SUM(TOTAL_LAID_OFF)
 FROM LAYOFFS_STAGE3
 GROUP BY COMPANY,YEAR(`DATE`)
 ),COMPANY_YEAR_RANK AS
 (SELECT*,DENSE_RANK() OVER (PARTITION BY YEARS ORDER BY TOTAL_LAID_OFF DESC) AS RANKING
 FROM COMPANY_YEAR
 WHERE YEARS IS NOT NULL
 )
 SELECT*
 FROM COMPANY_YEAR_RANK
 WHERE RANKING <= 5;
 
 

